### ISSUE TITLE
Utiliser des icones de Fontawsome? 

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#10]
De ce que j'ai lu dans les issues sur academicons, il n'y a pas github (par exemple) car il est disponible sur [fontawsome](https://fontawesome.com/) et academicons est une "extension académique" de fontawsome. 
Est-ce que j'ajoute fontawsome ou je télécharge les logos Github et Twitter? (pour plus tard: flux RSS)

**Comment by emchateau** [comment]
Comme je te disais, pour le moment tu peux simplement utiliser le CDN de même pour Font Awesome. Attention ce dernier service est en partie commercial même si le projet est GPL.

**Comment by lenaMK** [comment]
Quand je parlais de télécharger c'était pour les logos indidivudels. Oui on peut utiliser fontawsome avec le CDN mais mon hésitation était justement de nature politique

**Comment by lenaMK** [comment]
https://fontawesome.com/v5.15/icons/info-circle?style=regular

**Comment by emchateau** [comment]
Dans ce cas là, il vaut peut-être mieux cibler une bibliothèque moins commerciale ? Mais quel est le pb avec les CDN ? En dev je ne vois pas.
