### ISSUE TITLE
Lister les financements (et logos) à mettre sur le site

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#11]

**Comment by emchateau** [comment]
- [FCI](https://www.innovation.ca)
- [UdeM](http://www.bcrp.umontreal.ca/guide-normes/index.html)
Je ne pense pas qu’il soit nécessaire d’indiquer le CRSH car il ne finance pas directement le laboratoire. Il faut prévoir les logos dans les deux langues.
cf. https://www.innovation.ca/sites/default/files/file_uploads/guide_patch_2019_fr.pdf p. 58

**Comment by lenaMK** [comment]
je ne trouve pas les logos du gouvernement, même dans [communication](https://www.economie.gouv.qc.ca/bibliotheques/programmes/aide-financiere/programme-de-soutien-aux-organismes-de-recherche-et-dinnovation-pso/cofinancement-du-gouvernement-du-quebec-aux-programmes-de-la-fondation-canadienne-pour-linnovation-fci/communications/)

**Comment by emchateau** [comment]
Il faut contacter le Ministère pour obtenir le bon logo. Il faut insister pour obtenir le fichier vectoriel SVG ainsi que le guide d’utilisation graphique.
