### ISSUE TITLE
Coder la fonction de tri avec les tags

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#18]
interactivité pour sélectionner des contenus en cliquant sur un tag

**Comment by lenaMK** [comment]
@emchateau  J'ai trouvé ce site sur le showcase du discord Astro: il a une fonction de filtre avec les tags qui est statique (en gros il génère des pages pour chaque tag), je trouve que c'est très bien. ça te va aussi? 
view-source:https://publictransportforum.nz/tag/manawatu

**Comment by emchateau** [comment]
Fondamentalement c’est la logique d’un site statique que de créer des pages.
Mais si on veut seulement un filtre je dirais que nous aurions plutôt intérêt à faire ça dans l’interface.
Amitiés,
Emmanuel

**Comment by lenaMK** [comment]
à faire en statique

**Comment by lenaMK** [comment]
@emchateau J'ai terminé pour les actualités et je suis en train de faire la même chose pour les nouvelles mais je suis tombée sur deux problèmes.
1. j'avais mis des tags en 2 mots, exeples "visualisation 3D". J'ai résolu ça en remplaçant les espaces par des tirets pour l'url de la page (actualites/tags/visualisation-3D). Est-ce que ça te convient? 
2. C'est problématique pour l'URL quand il y a des accents dans les tags (CIÉCO, modélaiisation..). Je me doute que c'est possible de gérer les accents dans l'URL et/ou de les retirer avec une regex pour l'url. Est-ce que tu voudrais que je trouve une façon de le faire?

**Comment by lenaMK** [comment]
@emchateau c'est d'ici que vient le problème au build. Préfères-tu que j'annule le merge en attendant d'avoir tout réglé? (je dis "tout" mais je fais juste trouver bug après bug... le billinguisme, c'est quand même beaucoup à gérer)

**Comment by emchateau** [comment]
En toute logique, on ne devrait rien pousser sur la branche principale qui sert au déploiement qui présente des bugs. Tu pourrais faire une branche pour intégrer la nouvelle fonctionnalité. Quoiqu’il arrive comme ça casse le build le site reste dans la version antérieure. Donc tu peux te donner le temps de corriger si tu as besoin.

**Comment by lenaMK** [comment]
Désolée, j'avais oublié qu'il y avait un bug. 
Que voudrais-tu que je fasse pour gérer les URL? (cf mon commentaire de vendredi)

**Comment by lenaMK** [comment]
J'ai posé la question sur le discord Astro: https://discord.com/channels/830184174198718474/940336656978944000
@emchateau
