### ISSUE TITLE
Structurer architecture pour i18n 

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#19]
Voir où en est le projet documenté par entrée de blog dans leur i18n et mettre les bases pour la notre sans travailler sur les contenus pour le moment

**Comment by lenaMK** [comment]
Le gars a avancé mais pas encore terminé sa doc i18n. Par contre il utilise un CMS donc on ne voit pas les fichiers et il utilise react aussi: https://github.com/DefinedNet/nebula-docs
Je vais essayer quand même avec l'info que j'ai récupéré, et je vais voir si ça suffit :)

**Comment by emchateau** [comment]
Ok dac.
