### ISSUE TITLE
Bug submodule

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#32]
J'ai récupéré les modifs que tu as faites dans main, c'est du progrès par rapport à ce que j'avais avant mais n'empêche que quand je fais le submodule update j'ai encore une erreur

```bash
git submodule update --init --recursive

fatal: remote error: upload-pack: not our ref a0886a3a4b00050ab1d051f3e0bd169cc36a51f1
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'src/_labouvroir', but it did not contain a0886a3a4b00050ab1d051f3e0bd169cc36a51f1. Direct fetching of that commit failed.

```

**Comment by lenaMK** [comment]
J'ai la m'eme erreur si j'essaie de faire `git pull --recurse-submodules`

**Comment by emchateau** [comment]
Désolé, j’avais manqué ton issue. Comme dit tout à l’heure je vais modifier mes alertes pour les recevoir directement dans mon courriel pro.
En fait je n'ai pas le problème chez moi. Je te suggère de pousser tes modifications en faisant attention à ne pas pousser ce qui concerne le sous-module. Puis de scratcher le répertoire et de le réinstaller avec Github.

**Comment by lenaMK** [comment]
J'ai encore la même erreur: 

```bash
git clone --recursive https://github.com/ouvroir/ouvroir.github.io.git
Cloning into 'ouvroir.github.io'...
remote: Enumerating objects: 1455, done.
remote: Counting objects: 100% (899/899), done.
remote: Compressing objects: 100% (354/354), done.
remote: Total 1455 (delta 510), reused 771 (delta 411), pack-reused 556
Receiving objects: 100% (1455/1455), 2.22 MiB | 13.46 MiB/s, done.
Resolving deltas: 100% (815/815), done.
Submodule 'src/_labouvroir' (https://github.com/ouvroir/labouvroir.git) registered for path 'src/_labouvroir'
Cloning into '/home/lmk/Documents/ouvroir/ouvroir.github.io/src/_labouvroir'...
remote: Enumerating objects: 162, done.        
remote: Counting objects: 100% (162/162), done.        
remote: Compressing objects: 100% (119/119), done.        
remote: Total 162 (delta 75), reused 110 (delta 39), pack-reused 0        
Receiving objects: 100% (162/162), 64.50 KiB | 2.22 MiB/s, done.
Resolving deltas: 100% (75/75), done.
fatal: remote error: upload-pack: not our ref a0886a3a4b00050ab1d051f3e0bd169cc36a51f1
fatal: the remote end hung up unexpectedly
Fetched in submodule path 'src/_labouvroir', but it did not contain a0886a3a4b00050ab1d051f3e0bd169cc36a51f1. Direct fetching of that commit failed.
```

**Comment by lenaMK** [comment]
Essayer de reproduire le problème dans l'autre sens: 
1. créer un répertoire
2. mettre un sous-module dedenas
3. l'envaoyer à Emmanuel
4. faire un changement dans le sous-module
5. Emmanuel essaie de récupérer le-dit changement avec son sous-module

**Comment by lenaMK** [comment]
@emchateau  le repo test est là: https://github.com/ouvroir/testsubmodule

**Comment by lenaMK** [comment]
```bash
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git pull
Already up to date.
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git pull --recurse-submodules
Fetching submodule src/_labouvroir
From https://github.com/ouvroir/labouvroir
   64a8501..ec1f8a3  main       -> origin/main
Already up to date.
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git submodule update
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git status
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git submodule update --remote --merge
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'src/_labouvroir'
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git pull
Already up to date.
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git submodule update --remote --merge
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'src/_labouvroir'
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git submodule update
lmk@lenava-X1:~/Documents/ouvroir/testsubmodule$ git pull --recurse-submodules 
Fetching submodule src/_labouvroir
Already up to date.

```

**Comment by lenaMK** [comment]
https://miroslav-slapka.medium.com/handle-git-submodules-with-ease-55621afdb7bb

ça marche je pense, de mettre le submodule sur main (est-ce que ton ordi le ferait par défaut @emchateau ?)

**Comment by emchateau** [comment]
C’est une possibilité. C’est même normal avec Git de traiter main par défault.
J’essayerai lorsque tu auras ajouté la ligne à la config.

**Comment by lenaMK** [comment]
@emchateau Désolée, le trouble continue... 

J'ai essayé de modifier sur testsubmodule mais je ne peux plus pull or push. 
Quand je `git pull` j'ai un `fatal: Not possible to fast-forward, aborting.`

J'ai fait un `git diff main origin: 

```bash
diff --git a/src/_labouvroir b/src/_labouvroir
index eb59460..ec1f8a3 160000
--- a/src/_labouvroir
+++ b/src/_labouvroir
@@ -1 +1 @@
:...skipping...
diff --git a/src/_labouvroir b/src/_labouvroir
index eb59460..ec1f8a3 160000
--- a/src/_labouvroir
+++ b/src/_labouvroir
@@ -1 +1 @@
-Subproject commit eb59460c3b64262b0d352627656b47a6500bfb97
+Subproject commit ec1f8a3f24b36b572d7c8585fd4804281afb0597
```

**Comment by emchateau** [comment]
Pour ma part ça marche toujours
```txt
 ouvroir.github.io git:(main) git pull --recurse-submodules
Fetching submodule src/_labouvroir
From https://github.com/ouvroir/labouvroir
   05194a8..ef6f33b  main       -> origin/main
Already up to date.
```

**Comment by lenaMK** [comment]
C'est un repo test qu'ona vait créé pour essayer de débugger le problème de submodule: https://github.com/ouvroir/testsubmodule

**Comment by emchateau** [comment]
Du coup, ça marche toujours pour moi dessus.

Emmanuel Château-Dutier
Professeur adjoint

Faculté des arts et sciences,
Département d’histoire de l’art et d’études cinématographiques

Université de Montréal
Pavillon Lionel-Groulx, Bureau C-2067
3200, av. Jean-Brillant, Montréal QC
C.P. 6128, succursale Centre-ville, Montréal QC H3C 3J7

Tél.  +1 514 343-6026
***@***.*** | @emchateau

**Comment by lenaMK** [comment]
ça me semble logique vu que je ne peux plus ajouter mes modifs

**Comment by lenaMK** [comment]
@emchateau j'ai réussi à débloquer (le répertoire testsubmodule) en faisant un merge. J'ai push et chez moi le sous-module est à jour. Pourrais-tu pull de ton côté, voir s'il cause des problèmes éventuels?

**Comment by lenaMK** [comment]
@emchateau  super! J'ai poussé une modif dans labouvroir (cr d'aujourd'hui), on boucle la boucle? tu fais un update + push et j'essaie de pull?

**Comment by emchateau** [comment]
Merci pour le nouveau push.

➜  testsubmodule git:(main) git pull --recurse-submodules
Fetching submodule src/_labouvroir
From https://github.com/ouvroir/labouvroir
   a37072a..04dcb49  main       -> origin/main
Already up to date.

Ce qui me paraît normal comme on synchronise avec une version du dépôt.
