### ISSUE TITLE
Créer des pages pour l'équipe

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#33]
Créer une page par membre de l'équipe, en .md

**YAML frontmatter:** 
- nom: 
- prénom: 
- description: [poste]
- tags:
    - muséologie
    - modélisation 3D
    - partenariat CIÉCO
- mail: [courriel]
- link: [site web personnel]

autre? 

**Proposition de contenu:** 
bio / présentation

**Contenu automatisé:** 
- projets reliés 
- billets de blogue reliés
- autre?

**Comment by lenaMK** [comment]
@emchateau  et @ktanton-work si ça vous convient, est-ce que vous pourriez préparer ce contenu? Je vais faire le mien en exemple

**Comment by emchateau** [comment]
C’est super mais je me demande si nous devons créer une page individuelle sachant que nous avons pour certains d’entre nous d’autres profils ?

**Comment by lenaMK** [comment]
on peut lier vers vos pages personnelles aussi, je me disais que ça risquait de faire beaucoup de liens sortants plutôt que de créer une navigation au sein du site

**Comment by emchateau** [comment]
Oui tu as sans doute raison. Essayons avec des notices centrées sur ce que nous faisons dans le cadre du lab.

**Comment by lenaMK** [comment]
@ktanton-work as-tu un nom d'utilisatrice que tu utilises? 
Celui-ci servirait dans l'URL de ta page de présentation sur le site du labo, ex: https://ouvroir.umontreal.ca/fr/lab/lenamk/

**Comment by lenaMK** [comment]
@emchateau @ktanton-work  @WilliamDiakite 
Vos pages de bio respectives se trouvent ici: https://github.com/ouvroir/labouvroir/tree/main/equipe
À remplir quand vous avez un moment :)
