### ISSUE TITLE
Définir un premier design pour le site

### ISSUE THREAD

**Issue by lenaMK** [ouvroir/ouvroir.github.io#34]
utiliser spectre CSS et faire des petits ajustements
- choix de police: Open Sans? 
- définir le menu (nav) mobile
- jeu de couleurs : rouge corail #FF5757 
- faire un wireframe pour Menu, pied de page et grille? 

Inspiration ronds animation css: https://swissincss.com/tonhalle-quartett.html

**Comment by emchateau** [comment]
J’ai fait un peu de travail
- suppression d’un certain nombre de règles inutiles
- installation de la police complète
- stylage des titres
- début de travail sur la nav

**Comment by emchateau** [comment]
Pourquoi cette issue est-elle ouverte ?
Je pense qu’on peut la fermer.
